# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY . .

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Navigate to the app directory (if your FastAPI app is inside an 'app' folder)
WORKDIR /backend/app

# Run main.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]